In [87]:
from __future__ import print_function
import numpy as np
np.random.seed(2016)  # for reproducibility

from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, TimeDistributedDense
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM

In [88]:
print("Preparing int~binary dict...")
binary_dim = 4
ele_size = 2
largest_number = pow(2, binary_dim)

int2binary = {}    
for x in range(largest_num):    
    x_bStr = np.binary_repr(x, width = binary_dim)
    int2binary[x] = np.array(map(int, [c for c in x_bStr]))

print('Example: Init::Binary = 2::' + str(int2binary[2]))

Preparing int~binary dict...
Example: Init::Binary = 2::[0 0 1 0]


In [107]:
print("Preparing dataset...")
sample_size = 10000
X = np.zeros((sample_size, binary_dim, ele_size), dtype = int)
Y = np.zeros((sample_size, binary_dim, 1), dtype = int)
X_int = np.zeros((sample_size, ele_size))

for i in range(sample_size):
    for e in range(ele_size):
        ele_int = np.random.randint(largest_number / ele_size)
        ele = int2binary[ele_int]
        X[i, :, e] = ele
        X_int[i, e] = ele_int

Y_int = np.sum(X_int, axis = 1)
for i in range(len(Y_int)):
    Y[i, :, 0] = int2binary[Y_int[i]]

i = 2
print("Preview first %d samples of dataset X, X_int, Y, Y_int..." % i)
print(X[:i, :, :])
print(X_int[:i, :])
print(Y[:i, :])
print(Y_int[:i])
        

Preparing dataset...
Preview first 2 samples of dataset X, X_int, Y, Y_int...
[[[0 0]
  [1 0]
  [1 1]
  [0 1]]

 [[0 0]
  [0 0]
  [0 0]
  [1 1]]]
[[ 6.  3.]
 [ 1.  1.]]
[[[1]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [1]
  [0]]]
[ 9.  2.]


In [90]:
print("Model shapes")
alpha = 0.1
input_dim = ele_size
hidden_dim = 16
output_dim = 1

Model shapes


In [84]:
print("Building model refering to https://github.com/fchollet/keras/issues/168")
model = Sequential()
model.add(LSTM(hidden_dim, return_sequences=True, input_shape=(binary_dim, ele_size) ))
model.add(TimeDistributedDense(output_dim))
model.add(Activation('softmax')) #https://github.com/fchollet/keras/commit/8f2d6d2714aa1b60950a2fc355d39297b7f2cdfb

Building model refering to https://github.com/fchollet/keras/issues/168


In [85]:
print('Compile model...')
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

INFO (theano.gof.compilelock): Refreshing lock /Users/yunyan/.theano/compiledir_Darwin-15.3.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir/lock
INFO:theano.gof.compilelock:Refreshing lock /Users/yunyan/.theano/compiledir_Darwin-15.3.0-x86_64-i386-64bit-i386-2.7.11-64/lock_dir/lock


Compile model...


In [113]:
print('Training model...')
batch_size = 100
nb_epoch = 10
# for i in range(8):
model.fit(X, Y, batch_size=batch_size, nb_epoch=20, verbose = 0)


Training model...


In [114]:
print('Finished training and save model weights')
model.save_weights('my_model_weights.h5')

Finished training and save model weights
[WARNING] my_model_weights.h5 already exists - overwrite? [y/n]y
[TIP] Next time specify overwrite=True in save_weights!


In [115]:
print('Try perform add two number')
sample_size = 2
X_test = np.zeros((sample_size, binary_dim, ele_size), dtype = int)
Y_test = np.zeros((sample_size, binary_dim, 1), dtype = int)
X_int_test = np.zeros((sample_size, ele_size))

for i in range(sample_size):
    for e in range(ele_size):
        ele_int = np.random.randint(largest_number / ele_size)
        ele = int2binary[ele_int]
        X_test[i, :, e] = ele
        X_int_test[i, e] = ele_int

Y_int_test = np.sum(X_int_test, axis = 1)
for i in range(len(Y_int_test)):
    Y_test[i, :, 0] = int2binary[Y_int_test[i]]

i = sample_size
print(X_test[:i, :, :])
print(X_int_test[:i, :])
print(Y_test[:i, :])
print(Y_int_test[:i])

Try perform add two number
[[[0 0]
  [0 1]
  [1 0]
  [1 0]]

 [[0 0]
  [0 1]
  [1 1]
  [0 1]]]
[[ 3.  4.]
 [ 2.  7.]]
[[[0]
  [1]
  [1]
  [1]]

 [[1]
  [0]
  [0]
  [1]]]
[ 7.  9.]


In [118]:
classes = model.predict_classes(X_test)
proba = model.predict_proba(X_test)
preds = model.predict(X_test)

2/2 [==============================] - 0s


In [119]:
print(classes)
print(proba)
print(preds)

[[0 0 0 0]
 [0 0 0 0]]
[[[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]]
[[[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]]
